### ISSUE TITLE
Missing GeoLite file from latest GeoLite.mmdb release causing error

### ISSUE THREAD

**Issue by cda2** [daijro/camoufox#134] opened 2024-12-13 05:50 UTC
### Describe the bug:

The latest GeoLite.mmdb release does not include the GeoLite2-City.mmdb file, which ref in this line: https://github.com/daijro/camoufox/blob/9a9e61f6602db431b25e5c274d8e09e12dba96a0/pythonlib/camoufox/locale.py#L192

This might require fixing the build version or checking the GitHub repository's releases to ensure the GeoLite2-City.mmdb file is available.

### Logs:

```
#7 1.023 + python -m camoufox fetch
#7 4.399 Camoufox binaries up to date!
#7 4.399 Current version: v133.0-beta.19
#7 4.607 Traceback (most recent call last):
#7 4.607   File "<frozen runpy>", line 198, in _run_module_as_main
#7 4.607   File "<frozen runpy>", line 88, in _run_code
#7 4.608   File "/app/lib/python3.11/site-packages/camoufox/__main__.py", line 171, in <module>
#7 4.608     cli()
#7 4.609   File "/app/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
#7 4.610     return self.main(*args, **kwargs)
#7 4.610            ^^^^^^^^^^^^^^^^^^^^^^^^^^
#7 4.611   File "/app/lib/python3.11/site-packages/click/core.py", line 1078, in main
#7 4.611     rv = self.invoke(ctx)
#7 4.611          ^^^^^^^^^^^^^^^^
#7 4.611   File "/app/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
#7 4.612     return _process_result(sub_ctx.command.invoke(sub_ctx))
#7 4.612                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#7 4.613   File "/app/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
#7 4.613     return ctx.invoke(self.callback, **ctx.params)
#7 4.613            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#7 4.614   File "/app/lib/python3.11/site-packages/click/core.py", line 783, in invoke
#7 4.614     return __callback(*args, **kwargs)
#7 4.614            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
#7 4.614   File "/app/lib/python3.11/site-packages/camoufox/__main__.py", line 89, in fetch
#7 4.614     download_mmdb()
#7 4.615   File "/app/lib/python3.11/site-packages/camoufox/locale.py", line 212, in download_mmdb
#7 4.615     webdl(
#7 4.615   File "/app/lib/python3.11/site-packages/camoufox/pkgman.py", line 436, in webdl
#7 4.616     response.raise_for_status()
#7 4.616   File "/app/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
#7 4.618     raise HTTPError(http_error_msg, response=self)
#7 4.618 requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://github.com/P3TERX/GeoLite.mmdb/releases/download/2024.12.13/GeoLite2-City.mmdb
#7 ERROR: process "sh -exc python -m camoufox fetch" did not complete successfully: exit code: 1
```

### Screenshots:

![image](https://github.com/user-attachments/assets/20e9f35e-cfb0-4b9d-8962-eb9959295d2a)

### To Reproduce:

Run `camoufox fetch`

**Comment by daijro** [comment] 2024-12-13 07:04
This seems to be caused by an error in the release workflow used in the GeoLite.mmdb repo:

https://github.com/P3TERX/GeoLite.mmdb/issues/17

This issue is being caused by an bug in the master branch of `softprops/action-gh-release`:

https://github.com/softprops/action-gh-release/issues/556

---

A bug fix was just released in 0.4.9 that looks for assets in earlier releases until a fix is out.

**Closed by daijro** 2024-12-13 07:04 UTC
Labels: bug
