### ISSUE TITLE
Detected on Bet365 - Virtual Sports Page

### ISSUE THREAD

**Issue by rafaeltgt** [daijro/camoufox#83] opened 2024-11-16 12:55 UTC
### Website detecting Camoufox:

On virtual sports page, it should list the sports. When the content is empty, the bot is detected. 
URL: [https://www.bet365.com/#/AVR/B144/](https://www.bet365.com/#/AVR/B144/)

### Screenshots:

![camoufox-detected](https://github.com/user-attachments/assets/4bc3a2f8-8609-4507-89e7-ba6a744a2169)

### To Reproduce:

```python
from camoufox.sync_api import Camoufox

camoufox = Camoufox(humanize=True)
browser = camoufox.start()
page = browser.new_page()

page.goto("https://www.bet365.com/#/AVR/B144/")
```

### Version:

v132.0-beta.15

**Comment by daijro** [comment] 2024-11-17 06:13
Hello, thanks for reporting! I can't seem to reproduce this, so I have a couple of questions:

1. If you visit the site in a normal browser with a private tab, does this issue happen?
2. Does this always happen, or does it sometimes pass?
3. What OS are you using?

**Comment by daijro** [comment] 2024-11-19 12:34
> Hi, thanks for getting back to me!
> 
> It works on a regular browser, including in a private tab. The issue always occurs. I’m using Windows OS. Based on your screenshot, it seems you’re on the homepage. The page where the issue happens is "Virtual Sports." Here’s the direct link: https://www.bet365.com/#/AVR/B144/ or you can navigate to it via the sidebar on the left.
> 
> Let me know if you need any additional details!

Hello,

I was able to access the test site you linked with this URL instead (the one you've sent seems to redirect to the home page):
https://www.la.bet365.com/?_h=NwzL-tP5L1Tkp-_krqKReg%3D%3D&btsffd=1#/AS/B144/

I'm having trouble reproducing the pass case. The page seems to be cut off when I try to load it in my personal browser, but the all other pages of the site work. I've tried on Chrome and Firefox, Windows, Linux & Android, with US residential IP pools. I also can't seem to find the "Virtual Sports" on the left side panel or search either — I can only seem to access this site by directly visiting the URL, which might also be causing some issues.

> It works on a regular browser, including in a private tab.

I have a couple of questions to help me locate the issue, if you don't mind:

1. Do you happen to be using a proxy, or are spoofing the location or locale of Camoufox to a different target than your system browser is in where this site passes?
2. If you enter `camoufox test` in your Command Prompt, and try to manually navigate to the Virtual Sports page, does this error page still come up?
3. Are other sites Bet365 pages broken on Camoufox?

Thanks!

**Comment by rafaeltgt** [comment] 2024-11-21 00:21
Thank you for your help once again!

It seems like Virtual Sports might be restricted in certain countries. I'm currently accessing the platform from Brazil without using proxies or spoofing my location.

The issue persists when manually browsing via `camoufox test`. While the homepage appears to work fine, any section of the sidebar is blocked—not just "Virtual Sports." I’ve tested this with both my internet cable provider and 4G, but both are blocked as well.

I don’t know if this helps, but I was able to access the page using the standard `botasaurus` driver. However, I’d really prefer to use `camoufox`.

**Comment by daijro** [comment] 2024-11-22 04:33
![image](https://github.com/user-attachments/assets/fc1b56b9-56cb-4b20-a2cc-a8fed1db34c6)


Leak has been fixed in the latest version. Let me know how it works :+1:

**Closed by daijro** 2024-11-22 04:33 UTC
Labels: detection-issue, cant-reproduce
