### ISSUE TITLE
Geoip problem with async Camoufox

### ISSUE THREAD

**Issue by MaxAndolini** [daijro/camoufox#31] opened 2024-10-10 14:15 UTC
### Describe the bug:

After 0.2.6 version, this error pops up;

AttributeError: 'dict' object has no attribute 'endswith'

### Screenshots:

![image](https://github.com/user-attachments/assets/acaf3bb6-80a6-4087-93eb-864ba55caa0d)

### To Reproduce:

```
with Camoufox(
    proxy={'server': f'http://{proxy_1[0]}:{proxy_1[1]}', 'username': proxy_1[2],
                                                'password': proxy_1[3]}
) as browser:
    page = browser.new_page()
    page.goto("https://www.browserscan.net")
```

### Version:

0.2.11

**Comment by daijro** [comment] 2024-10-10 20:45
Fixed in 0.2.12. The issue was caused by parameters being sent to a method in the wrong order.

**Closed by daijro** 2024-10-10 20:45 UTC
Labels: bug
